 DECLARE @RUT AS VARCHAR(10)
 DECLARE @TEXTO AS VARCHAR(50)
 DECLARE CURSORITO CURSOR FOR
	SELECT RUT FROM USUARIOS
 OPEN CURSORITO
 
      
  FETCH NEXT FROM CURSORITO INTO @RUT

    WHILE @@FETCH_STATUS = 0
    BEGIN
       EXEC SP_VALIDA_RUT @RUT, @TEXTO OUTPUT
	   UPDATE USUARIOS SET ESTADO = @TEXTO WHERE RUT = @RUT
	   FETCH NEXT FROM CURSORITO INTO @RUT
    END

    CLOSE CURSORITO
    DEALLOCATE CURSORITO