 -- TAREA 2 CORRECCION
 -- PROFESOR: JUAN CARLOS ÁVILA

 -- OBJETIVO: MEDIANTE UN CURSOR, RECORRER LA TABLA USUARIOS CON EL FIN DE OBTENER EL RUT Y EJECUTAR PROCEDIMIENTO ALMACENADO QUE VALIDA RUT, ACTUALIZANDO EL ESTADO EN LA BASE DE DATOS
 -- NIVEL DE COMPLEJIDAD : 5 ESTRELLAS
 -- FECHA : 22-08-2022

 
 DECLARE @TEXTO AS VARCHAR(50)
 DECLARE @RUT AS VARCHAR(10)
 DECLARE @resultado AS VARCHAR(50)

 DECLARE CURSORITO CURSOR FOR
	SELECT RUT FROM USUARIOS
 OPEN CURSORITO
       
  FETCH NEXT FROM CURSORITO INTO @RUT

    WHILE @@FETCH_STATUS = 0
    BEGIN
        EXECUTE SP_VALIDA_RUT @RUT, @resultado OUTPUT			  --JCA 22/08/2022   ACA ESTA LA SOLUCION DEL PROBLEMA
		UPDATE USUARIOS SET ESTADO = @resultado WHERE RUT = @RUT  --JCA 22/08/2022   ACA ACTUALIZLA TABLA CON EL RESULTADO #XUPATESA
	    FETCH NEXT FROM CURSORITO INTO @RUT
    END

    CLOSE		CURSORITO
    DEALLOCATE	CURSORITO


--DATOS PARA REVISAR
	SELECT *,'PRENDANME VELAS' AS XUPATESA  FROM USUARIOS