alter PROCEDURE SP_VALIDA_RUT @RUT AS VARCHAR(50), @TEXTO AS VARCHAR(50) OUTPUT
AS 
BEGIN

--DECLARE @RUT		AS VARCHAR(50)
DECLARE @SUMA		AS INT 
DECLARE @CONTA		AS INT 
DECLARE @DAS		AS INT 
DECLARE @VALOR		AS INT  
DECLARE @DV			AS varchar(100) 
DECLARE @CALCULODF	as int 

SET @SUMA = 0
 
SET @CONTA = 1 
SET @DAS = 3
SET @VALOR = 0
SET @DV = SUBSTRING (@RUT,10,1) 
 
WHILE @CONTA <= 8
BEGIN	 
	SET @VALOR =  SUBSTRING (@RUT,@CONTA,1)
	SET @SUMA = @SUMA +(@VALOR * @DAS)
	SET @DAS = @DAS - 1 

	IF @DAS = 1 
		SET @DAS = 7
	SET @CONTA = @CONTA +1	
END	
	 
SET @CALCULODF = 11 - (@SUMA % 11)
if @CALCULODF = 11 --0
 set @CALCULODF= 0

 if @CALCULODF = 10 --k
	if @DV = 'K'
		SET @TEXTO = 'CORRECTO '
	else 
		SET @TEXTO = 'INCORRECTO'

else

IF @CALCULODF = @DV 
	SET @TEXTO = 'CORRECTO'
ELSE
	SET @TEXTO = 'INCORRECTO'


END
