ALTER PROCEDURE SP_VALIDA_RUT @RUT AS VARCHAR(50)

	
AS 
BEGIN

--DECLARE @RUT		AS VARCHAR(50)
DECLARE @SUMA		AS INT 
DECLARE @CONTA		AS INT 
DECLARE @DAS		AS INT 
DECLARE @VALOR		AS INT  
DECLARE @DV			AS INT 
DECLARE @CALCULODF	AS INT 

SET @SUMA = 0
SET @RUT = '21240484-K'
SET @CONTA = 1 
SET @DAS = 3
SET @VALOR = 0
SET @DV = SUBSTRING (@RUT,10,1) 


--PRINT 'eL DIGITO VERIFICADOR ES : ' + CONVERT (CHAR, @DV)

WHILE @CONTA <= 8
BEGIN	

	SET @VALOR =  SUBSTRING (@RUT,@CONTA,1)
	SET @SUMA = @SUMA +(@VALOR * @DAS)
	SET @DAS = @DAS - 1 

	IF @DAS = 1 
		SET @DAS = 7
	SET @CONTA = @CONTA +1

	
END	
	 
SET @CALCULODF = 11 - (@SUMA % 11)

SET @dv = (CONVERT(VARCHAR(20),@CALCULODF));

IF @CALCULODF = 11
	BEGIN
		SET	@DV ='0'
	END
	IF @CALCULODF = 10
	BEGIN
		SET @DV = 'K'
		END

IF @CALCULODF = @DV 

	PRINT 'CORRECTO'
ELSE
	PRINT 'INCORRECTO'


END



