/* CLASE DE RECUPERACION DE TALLER DE BASES DE DATOS
PROFESOR: JUAN CARLOS ÁVILA
FECHA : 19-10-2022
*/


CREATE DATABASE RESTORANT
GO
USE RESTORANT 
GO

CREATE TABLE PEDIDO (ID INT IDENTITY PRIMARY KEY,
                     DETALLE VARCHAR(50),
					 MESA INT,
					 ESTADO VARCHAR(10))


CREATE TABLE COCINA (ID INT IDENTITY PRIMARY KEY,
                     DETALLE_PLATO VARCHAR(50)	,				 
					 ESTADO VARCHAR(10))

		CREATE TABLE CAJA (ID INT IDENTITY PRIMARY KEY,
                     DETALLE VARCHAR(50),
					
					 ESTADO VARCHAR(10))

SELECT * FROM CAJA

SELECT * FROM PEDIDO

SELECT * FROM COCINA

SELECT * FROM BITACORA

INSERT INTO PEDIDO VALUES ('TOCOMPLE', 8,NULL)

UPDATE COCINA SET ESTADO = 'TER' WHERE ID =7


ALTER TRIGGER TG_PASA_A_COCINA
ON PEDIDO
FOR INSERT
AS
BEGIN

     DECLARE @PEDIDO VARCHAR(50)
	 SELECT @PEDIDO = DETALLE FROM inserted
	 INSERT INTO COCINA VALUES (@PEDIDO, 'PREP')

END


CREATE TRIGGER TG_PASA_A_CAJA
ON COCINA
FOR UPDATE
AS
BEGIN

     DECLARE @PEDIDO VARCHAR(50)
	 SELECT @PEDIDO = DETALLE_PLATO FROM inserted
	 UPDATE PEDIDO SET ESTADO = 'LISTO' WHERE DETALLE = @PEDIDO

END



ALTER TRIGGER TG_PASA_A_BITACORA
ON PEDIDO
FOR UPDATE
AS
BEGIN

     DECLARE @ID INT
	 SELECT @ID = ID FROM deleted

	 DECLARE @IP VARCHAR(50)

	-- SELECT * FROM SYS.dm_exec_connections WHERE session_id = @@SPID
	 INSERT INTO BITACORA VALUES ( CONVERT(CHAR,serverproperty('ComputerNamePhysicalNetBIOS')) , GETDATE(),@ID)

END




CREATE TABLE BITACORA (ID INT IDENTITY PRIMARY KEY,
                     IP_PC VARCHAR(50)	,				 
					 HORA VARCHAR(50),
					 ID_PEDIDO_LISTO INT
					 )









INSERT INTO CAJA VALUES ('DETALLE 2', NULL)


CREATE TRIGGER TG_ANALIZA_CAJA
ON CAJA
FOR UPDATE
AS
BEGIN

     SELECT * FROM INSERTED
	 SELECT * FROM deleted


END


UPDATE CAJA SET DETALLE ='NUEVO DETALLE 1',ESTAdo ='PAGAD' WHERE ID = 1