/* CLASE DE RECUPERACION DE TALLER DE BASES DE DATOS
PROFESOR: JUAN CARLOS ÁVILA
FECHA : 19-10-2022
*/


CREATE DATABASE RESTORANT
GO
USE RESTORANT 
GO

CREATE TABLE PEDIDO (ID INT IDENTITY PRIMARY KEY,
                     DETALLE VARCHAR(50),
					 MESA INT,
					 ESTADO VARCHAR(10))


CREATE TABLE COCINA (ID INT IDENTITY PRIMARY KEY,
                     DETALLE_PLATO VARCHAR(50)	,				 
					 ESTADO VARCHAR(10))

		CREATE TABLE CAJA (ID INT IDENTITY PRIMARY KEY,
                     DETALLE VARCHAR(50),
					
					 ESTADO VARCHAR(10))


SELECT * FROM PEDIDO

SELECT * FROM COCINA
SELECT * FROM CAJA


INSERT INTO PEDIDO VALUES ('SALCHIPAPAS', 3,NULL)

UPDATE COCINA SET ESTADO = 'TER' WHERE ID =5


ALTER TRIGGER TG_PASA_A_COCINA
ON PEDIDO
FOR INSERT
AS
BEGIN

     DECLARE @PEDIDO VARCHAR(50)
	 SELECT @PEDIDO = DETALLE FROM inserted
	 INSERT INTO COCINA VALUES (@PEDIDO, 'PREP')

END


CREATE TRIGGER TG_PASA_A_CAJA
ON COCINA
FOR UPDATE
AS
BEGIN

     DECLARE @PEDIDO VARCHAR(50)
	 SELECT @PEDIDO = DETALLE_PLATO FROM inserted
	 UPDATE PEDIDO SET ESTADO = 'LISTO' WHERE DETALLE = @PEDIDO

END