 -- TAREA 1 CORRECCION
 -- PROFESOR: JUAN CARLOS ÁVILA

 -- OBJETIVO: CREAR PROCEDIMIENTO ALMACENADO PARA ALGORITMO DE VALIDACION DE RUT ANALIZADO EN CLASE.(INCLUYE TAREA DE VALIDAR GUION 0 Y K
 -- NIVEL DE COMPLEJIDAD : 3 ESTRELLAS
 -- FECHA : 19-08-2022



CREATE PROCEDURE SP_VALIDA_RUT @RUT AS VARCHAR(50),  @RESULTADO VARCHAR(50) OUTPUT
AS 
BEGIN
		DECLARE @SUMA		AS INT 
		DECLARE @CONTA		AS INT 
		DECLARE @DAS		AS INT 
		DECLARE @VALOR		AS INT  
		DECLARE @DV			AS VARCHAR(100) 
		DECLARE @CALCULODF	AS INT 
		SET @SUMA = 0 
		SET @CONTA = 1 
		SET @DAS = 3
		SET @VALOR = 0
		SET @DV = SUBSTRING (@RUT,10,1) 
 
		WHILE @CONTA <= 8
		BEGIN	 
			SET @VALOR =  SUBSTRING (@RUT,@CONTA,1)
			SET @SUMA = @SUMA +(@VALOR * @DAS)
			SET @DAS = @DAS - 1 

			IF @DAS = 1 
				SET @DAS = 7
			SET @CONTA = @CONTA +1	
		END	
	 
		SET @CALCULODF = 11 - (@SUMA % 11)
		IF @CALCULODF = 11 --0
		 SET @CALCULODF= 0

		 IF @CALCULODF = 10 --K
			IF @DV = 'K'
				SET  @RESULTADO= 'CORRECTO '
			ELSE 
				SET @RESULTADO ='INCORRECTO'
		ELSE
		IF @CALCULODF = @DV 
			SET @RESULTADO = 'CORRECTO'
		ELSE
			SET @RESULTADO = 'INCORRECTO'
		RETURN  
END
