create database TRABAJO_FJF
use TRABAJO_FJF

---------------Creacion de tablas-------------------------
create table PROYECTO
(
ID_PROYECTO				varchar(10),
NOMBRE_PROYECTO			varchar(20) PRIMARY KEY NOT NULL,
FECHA_AVISO				varchar(20),
FECHA_ENTREGA			varchar(20),
VALOR_PROYECTO			float,
ID_IMPORTANCIA			varchar(5),
ID_ESTADO				varchar(5),
ID_ESTADO_FINAL			varchar(10)
)
drop table PROYECTO
---------------------------------------------------------
create table DIRECCION_PROYECTO
(
ID_PROYECTO				varchar(10) PRIMARY KEY NOT NULL,
NOMBRE_DIRECCION		varchar(1000),
ID_DEPARTAMENTO			varchar(5),
ID_COMUNA				varchar(5)
)

---------------------------------------------------------
create table IMPORTANCIA
(
ID_IMPORTANCIA			varchar(5) PRIMARY KEY NOT NULL,
DETALLE_IMPORTANCIA		varchar(30)
)
drop table IMPORTANCIA
---------------------------------------------------------
create table DEPARTAMENTO
(
ID_DEPARTAMENTO			varchar(5) PRIMARY KEY NOT NULL,
DETALLE_DEPARTAMENTEO	varchar(30)
)

---------------------------------------------------------
create table COMUNA
(
ID_COMUNA				varchar(5) PRIMARY KEY NOT NULL,
DETALLE_COMUNA			varchar(30)
)

---------------------------------------------------------
create table ESTADO
(
ID_ESTADO				varchar(5) PRIMARY KEY NOT NULL,
DETALLE_ESTADO			varchar(30)
)

---------------------------------------------------------
create table ESTADO_FINAL
(
ID_ESTADO_FINAL			varchar(10) PRIMARY KEY NOT NULL,
DETALLE_ESTADO_FINAL	varchar(30)
)

drop table ESTADO_FINAL
-----------------Bulk insert de tablas con sus datos-----------------------

bulk insert PROYECTO From 'C:\DATOS 3FN\Proyecto.txt'
With
(
FIRSTROW = 2
)

bulk insert DIRECCION_PROYECTO From 'C:\DATOS 3FN\DIRECCION_PROYECTO.txt'
With
(
FIRSTROW = 2
)

bulk insert IMPORTANCIA From 'C:\DATOS 3FN\Importancia.txt'
With
(
FIRSTROW = 2
)

bulk insert DEPARTAMENTO From 'C:\DATOS 3FN\Departamento .txt'
With
(
FIRSTROW = 2
)

bulk insert COMUNA From 'C:\DATOS 3FN\Comuna.txt'
With
(
FIRSTROW = 2
)

bulk insert ESTADO From 'C:\DATOS 3FN\Estado.txt'
With
(
FIRSTROW = 2
)

bulk insert ESTADO_FINAL From 'C:\DATOS 3FN\Estado_Final.txt'
With
(
FIRSTROW = 2
)

-------------------------------------------------------------------
select * from PROYECTO
select * from DIRECCION_PROYECTO
select * from IMPORTANCIA                                       
select * from DEPARTAMENTO
select * from COMUNA
select * from ESTADO
select * from ESTADO_FINAL
                                                  
-------------------------------------------------------------------
TRUNCATE TABLE PROYECTO
TRUNCATE TABLE DIRECCION_PROYECTO
TRUNCATE TABLE IMPORTANCIA
TRUNCATE TABLE DEPARTAMENTO
TRUNCATE TABLE COMUNA
TRUNCATE TABLE ESTADO
TRUNCATE TABLE ESTADO_FINAL

--------------------------------------------------------------------

select DIREC.ID_PROYECTO, PRY.NOMBRE_PROYECTO, PRY.FECHA_AVISO, PRY.FECHA_ENTREGA, PRY.VALOR_PROYECTO, IMP.ID_IMPORTANCIA, EST.ID_ESTADO, ESTF.ID_ESTADO_FINAL from PROYECTO as PRY	
								inner join IMPORTANCIA			as IMP		on PRY.ID_IMPORTANCIA = IMP.ID_IMPORTANCIA 
								inner join ESTADO				as EST		on PRY.ID_ESTADO = EST.ID_ESTADO
								inner join ESTADO_FINAL			as ESTF		on PRY.ID_ESTADO_FINAL = ESTF.ID_ESTADO_FINAL
								inner join DIRECCION_PROYECTO	as DIREC	on PRY.ID_PROYECTO = DIREC.ID_PROYECTO
								inner join DEPARTAMENTO			as DEPA		on DIREC.ID_DEPARTAMENTO = DEPA.ID_DEPARTAMENTO
								inner join COMUNA				as COMUN	on DIREC.ID_COMUNA = COMUN.ID_COMUNA

select DIREC_PRY.ID_PROYECTO, DIREC_PRY.NOMBRE_DIRECCION, DEPA.ID_DEPARTAMENTO, COMUN.ID_COMUNA from DIRECCION_PROYECTO as DIREC_PRY
								inner join DEPARTAMENTO			as DEPA		on DIREC_PRY.ID_DEPARTAMENTO = depa.ID_DEPARTAMENTO
								inner join comuna				as COMUN	on DIREC_PRY.ID_COMUNA = COMUN.ID_COMUNA

select DIRECCION_PROYECTO.ID_PROYECTO, DIRECCION_PROYECTO.NOMBRE_DIRECCION, COMUNA.ID_COMUNA, COMUNA.DETALLE_COMUNA from DIRECCION_PROYECTO 
								inner join COMUNA							on DIRECCION_PROYECTO.ID_COMUNA = COMUNA.ID_COMUNA

---------------COUNT-------------------------

SELECT NOMBRE_DIRECCION,		  COUNT(*) AS TOTAL FROM DIRECCION_PROYECTO GROUP BY NOMBRE_DIRECCION	ORDER BY 1
SELECT NOMBRE_DIRECCION,		  COUNT(*) AS TOTAL FROM DIRECCION_PROYECTO GROUP BY NOMBRE_DIRECCION	ORDER BY NOMBRE_DIRECCION DESC
SELECT VALOR_PROYECTO,			  COUNT(*) AS TOTAL FROM PROYECTO			GROUP BY VALOR_PROYECTO		HAVING COUNT(*) < 227865
SELECT DETALLE_ESTADO_FINAL,      COUNT(*) AS TOTAL FROM ESTADO_FINAL		GROUP BY DETALLE_ESTADO_FINAL
SELECT DETALLE_ESTADO, COUNT(*) AS TOTAL FROM ESTADO				GROUP BY  DETALLE_ESTADO
SELECT							  COUNT(*) AS 'CONTROL DE PERDIDAS'	FROM DIRECCION_PROYECTO WHERE ID_DEPARTAMENTO = 'D-002'
SELECT							  COUNT(*) AS URGENCIA FROM PROYECTO WHERE ID_IMPORTANCIA = 'I-2'


---------------------------------------------------
select  ID_PROYECTO, NOMBRE_PROYECTO,FECHA_AVISO, FECHA_ENTREGA from PROYECTO 

select distinct ID_COMUNA from DIRECCION_PROYECTO order by ID_COMUNA desc

select sum(VALOR_PROYECTO) as 'suma de los proyectos ' from PROYECTO

select round(VALOR_PROYECTO,0) as 'Valor sin decimal' from PROYECTO

select * from DIRECCION_PROYECTO where ID_DEPARTAMENTO = 'D-008'

select * from PROYECTO where ID_IMPORTANCIA = 'I-1' and ID_ESTADO = 'E-3'

select ID_PROYECTO, VALOR_PROYECTO, ID_ESTADO_FINAL from PROYECTO where VALOR_PROYECTO = 301950 or VALOR_PROYECTO = 422053.5

select * from DIRECCION_PROYECTO where not NOMBRE_DIRECCION = 'MONSEÑOR ESCRIVA DE BALAGUER 22699 '

select max(VALOR_PROYECTO) as 'Valor mas alto' from PROYECTO

select min(VALOR_PROYECTO) as 'valor mas pequeño' from PROYECTO

select NOMBRE_PROYECTO from PROYECTO where ID_IMPORTANCIA is null

select ID_PROYECTO, ID_ESTADO, ID_ESTADO_FINAL from PROYECTO

SELECT ID_IMPORTANCIA, DETALLE_IMPORTANCIA FROM IMPORTANCIA 

------------------update(ID_COMUNA)----------------------------------------

update DIRECCION_PROYECTO set ID_COMUNA ='C-001' where ID_COMUNA = 'C-1'
update DIRECCION_PROYECTO set ID_COMUNA ='C-002' where ID_COMUNA = 'C-2'
update DIRECCION_PROYECTO set ID_COMUNA ='C-003' where ID_COMUNA = 'C-3'
update DIRECCION_PROYECTO set ID_COMUNA ='C-004' where ID_COMUNA = 'C-4'
update DIRECCION_PROYECTO set ID_COMUNA ='C-005' where ID_COMUNA = 'C-5'
update DIRECCION_PROYECTO set ID_COMUNA ='C-006' where ID_COMUNA = 'C-6'
update DIRECCION_PROYECTO set ID_COMUNA ='C-007' where ID_COMUNA = 'C-7'
update DIRECCION_PROYECTO set ID_COMUNA ='C-008' where ID_COMUNA = 'C-8'
update DIRECCION_PROYECTO set ID_COMUNA ='C-009' where ID_COMUNA = 'C-9'
update DIRECCION_PROYECTO set ID_COMUNA ='C-010' where ID_COMUNA = 'C-10'
update DIRECCION_PROYECTO set ID_COMUNA ='C-011' where ID_COMUNA = 'C-11'
update DIRECCION_PROYECTO set ID_COMUNA ='C-012' where ID_COMUNA = 'C-12'
update DIRECCION_PROYECTO set ID_COMUNA ='C-013' where ID_COMUNA = 'C-13'
update DIRECCION_PROYECTO set ID_COMUNA ='C-014' where ID_COMUNA = 'C-14'
update DIRECCION_PROYECTO set ID_COMUNA ='C-015' where ID_COMUNA = 'C-15'
update DIRECCION_PROYECTO set ID_COMUNA ='C-016' where ID_COMUNA = 'C-16'
update DIRECCION_PROYECTO set ID_COMUNA ='C-017' where ID_COMUNA = 'C-17'
update DIRECCION_PROYECTO set ID_COMUNA ='C-018' where ID_COMUNA = 'C-18'
update DIRECCION_PROYECTO set ID_COMUNA ='C-019' where ID_COMUNA = 'C-19'
update DIRECCION_PROYECTO set ID_COMUNA ='C-020' where ID_COMUNA = 'C-20'
update DIRECCION_PROYECTO set ID_COMUNA ='C-021' where ID_COMUNA = 'C-21'
update DIRECCION_PROYECTO set ID_COMUNA ='C-022' where ID_COMUNA = 'C-22'
update DIRECCION_PROYECTO set ID_COMUNA ='C-023' where ID_COMUNA = 'C-23'
update DIRECCION_PROYECTO set ID_COMUNA ='C-024' where ID_COMUNA = 'C-24'
update DIRECCION_PROYECTO set ID_COMUNA ='C-025' where ID_COMUNA = 'C-25'
update DIRECCION_PROYECTO set ID_COMUNA ='C-026' where ID_COMUNA = 'C-26'
update DIRECCION_PROYECTO set ID_COMUNA ='C-027' where ID_COMUNA = 'C-27'
update DIRECCION_PROYECTO set ID_COMUNA ='C-028' where ID_COMUNA = 'C-28'
update DIRECCION_PROYECTO set ID_COMUNA ='C-029' where ID_COMUNA = 'C-29'
update DIRECCION_PROYECTO set ID_COMUNA ='C-030' where ID_COMUNA = 'C-30'
update DIRECCION_PROYECTO set ID_COMUNA ='C-031' where ID_COMUNA = 'C-31'
update DIRECCION_PROYECTO set ID_COMUNA ='C-032' where ID_COMUNA = 'C-32'
----------------update(ID_DEPARTAMENTO)---------------------------------
UPDATE DIRECCION_PROYECTO SET ID_DEPARTAMENTO = 'D-001' WHERE ID_DEPARTAMENTO = 'D-1'
UPDATE DIRECCION_PROYECTO SET ID_DEPARTAMENTO = 'D-002' WHERE ID_DEPARTAMENTO = 'D-2'
UPDATE DIRECCION_PROYECTO SET ID_DEPARTAMENTO = 'D-003' WHERE ID_DEPARTAMENTO = 'D-3'
UPDATE DIRECCION_PROYECTO SET ID_DEPARTAMENTO = 'D-004' WHERE ID_DEPARTAMENTO = 'D-4'
UPDATE DIRECCION_PROYECTO SET ID_DEPARTAMENTO = 'D-005' WHERE ID_DEPARTAMENTO = 'D-5'
UPDATE DIRECCION_PROYECTO SET ID_DEPARTAMENTO = 'D-006' WHERE ID_DEPARTAMENTO = 'D-6'
UPDATE DIRECCION_PROYECTO SET ID_DEPARTAMENTO = 'D-007' WHERE ID_DEPARTAMENTO = 'D-7'
UPDATE DIRECCION_PROYECTO SET ID_DEPARTAMENTO = 'D-008' WHERE ID_DEPARTAMENTO = 'D-8'
UPDATE DIRECCION_PROYECTO SET ID_DEPARTAMENTO = 'D-009' WHERE ID_DEPARTAMENTO = 'D-9'
UPDATE DIRECCION_PROYECTO SET ID_DEPARTAMENTO = 'D-010' WHERE ID_DEPARTAMENTO = 'D-10'
-------------------------------------------------------------------------
UPDATE DEPARTAMENTO SET ID_DEPARTAMENTO = 'D-001' WHERE ID_DEPARTAMENTO = 'D-1'
UPDATE DEPARTAMENTO SET ID_DEPARTAMENTO = 'D-002' WHERE ID_DEPARTAMENTO = 'D-2'
UPDATE DEPARTAMENTO SET ID_DEPARTAMENTO = 'D-003' WHERE ID_DEPARTAMENTO = 'D-3'
UPDATE DEPARTAMENTO SET ID_DEPARTAMENTO = 'D-004' WHERE ID_DEPARTAMENTO = 'D-4'
UPDATE DEPARTAMENTO SET ID_DEPARTAMENTO = 'D-005' WHERE ID_DEPARTAMENTO = 'D-5'
UPDATE DEPARTAMENTO SET ID_DEPARTAMENTO = 'D-006' WHERE ID_DEPARTAMENTO = 'D-6'
UPDATE DEPARTAMENTO SET ID_DEPARTAMENTO = 'D-007' WHERE ID_DEPARTAMENTO = 'D-7'
UPDATE DEPARTAMENTO SET ID_DEPARTAMENTO = 'D-008' WHERE ID_DEPARTAMENTO = 'D-8'
UPDATE DEPARTAMENTO SET ID_DEPARTAMENTO = 'D-009' WHERE ID_DEPARTAMENTO = 'D-9'
UPDATE DEPARTAMENTO SET ID_DEPARTAMENTO = 'D-010' WHERE ID_DEPARTAMENTO = 'D-10'
-------------------------------------------------------------------------
UPDATE PROYECTO SET ID_ESTADO_FINAL = 'EF-001' WHERE ID_ESTADO_FINAL = 'EF-1'
UPDATE PROYECTO SET ID_ESTADO_FINAL = 'EF-002' WHERE ID_ESTADO_FINAL = 'EF-2'
UPDATE PROYECTO SET ID_ESTADO_FINAL = 'EF-002' WHERE ID_ESTADO_FINAL = 'EF-3'
UPDATE PROYECTO SET ID_ESTADO_FINAL = 'EF-004' WHERE ID_ESTADO_FINAL = 'EF-4'
UPDATE PROYECTO SET ID_ESTADO_FINAL = 'EF-005' WHERE ID_ESTADO_FINAL = 'EF-5'
UPDATE PROYECTO SET ID_ESTADO_FINAL = 'EF-006' WHERE ID_ESTADO_FINAL = 'EF-6'
UPDATE PROYECTO SET ID_ESTADO_FINAL = 'EF-007' WHERE ID_ESTADO_FINAL = 'EF-7'
UPDATE PROYECTO SET ID_ESTADO_FINAL = 'EF-008' WHERE ID_ESTADO_FINAL = 'EF-8'
UPDATE PROYECTO SET ID_ESTADO_FINAL = 'EF-009' WHERE ID_ESTADO_FINAL = 'EF-9'
UPDATE PROYECTO SET ID_ESTADO_FINAL = 'EF-010' WHERE ID_ESTADO_FINAL = 'EF-10'

-------------------------------------------------------------------------
update DIRECCION_PROYECTO set NOMBRE_DIRECCION = replace(NOMBRE_DIRECCION, 'ñ','Ñ') where NOMBRE_DIRECCION like '%ñ%'
-------------------------------------------------------------------------

CREATE VIEW VISTA_URGENTE_VS_NORMAL
AS 
SELECT DETALLE_IMPORTANCIA, COUNT(*) AS 'TOTAL PERSONAS'
FROM IMPORTANCIA INNER JOIN PROYECTO ON PROYECTO.ID_IMPORTANCIA = IMPORTANCIA.ID_IMPORTANCIA 
GROUP BY DETALLE_IMPORTANCIA

-------------------------------------------------------------------------
create view VISTA_NOMBRE_DIRECCION_CON_COMUNA
AS 
SELECT DETALLE_DEPARTAMENTEO,COUNT(*) AS TOTAL
FROM DEPARTAMENTO INNER JOIN DIRECCION_PROYECTO ON DIRECCION_PROYECTO.ID_DEPARTAMENTO = DEPARTAMENTO.ID_DEPARTAMENTO
GROUP BY DETALLE_DEPARTAMENTEO
-------------------------------------------------------------------------
CREATE VIEW VISTA_CUANTAS_COMUNAS_POR_DEPARTAMENTOS
AS 
SELECT DETALLE_COMUNA, COUNT(*) AS TOTAL
FROM COMUNA INNER JOIN DIRECCION_PROYECTO ON  DIRECCION_PROYECTO.ID_COMUNA = COMUNA.ID_COMUNA
GROUP BY DETALLE_COMUNA

